# DEVELOP NEW CONCEPT

on:
  push:
    branches:
    - master
    - develop
  workflow_dispatch:
    inputs:
      deploy:
        description: deploy manual
        required: true
        options:
        - prod
        - staging

      # staging:
        # description: deploy manually to staging
        # required: true
        # default: "staging"
      # sit:
      #   description: deploy manually to SIT
      #   required: true
      #   default: "sit"
      


jobs:

  deploy_SIT_DEVELOP:
    name: deploy to SIT branch DEVELOP
    # if: ${{ github.event.inputs.sit == 'sit' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout branch #tambahin sendiri
        run: |
          echo "complete checkout"

      - name: Configure AWS credentials
        run: |
          echo "complete configure aws"

      - name: Login to Amazon ECR
        run: |
          echo "complete ECR"


  deploy_PROD_MASTER:
    name: deploy to PROD branch MASTER
    if: ${{ github.event.inputs.deploy == 'prod' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout branch #tambahin sendiri
        run: |
          echo "complete checkout"

      - name: Configure AWS credentials
        run: |
          echo "complete configure aws"

      - name: Login to Amazon ECR
        run: |
          echo "complete ECR"

  deploy_STAGING_DEVELOP:
    name: deploy to PROD branch MASTER
    if: ${{ github.event.inputs.deploy == 'staging' }}
    needs: ['deploy_SIT_DEVELOP']
    runs-on: ubuntu-latest

    steps:
      - name: checkout branch #tambahin sendiri
        run: |
          echo "complete checkout"

      - name: Configure AWS credentials
        run: |
          echo "complete configure aws"

      - name: Login to Amazon ECR
        run: |
          echo "complete ECR"
 
